version: 2
jobs:

  test:
    docker:
      - image: circleci/node:12.7.0
    steps:
      - checkout

      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: npm test
          command: CI=true npm test

  deploy: &deploy
    docker:
      - image: circleci/node:12.7.0
    steps:
      - checkout

      - restore_cache:
          key: npm-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: npm run build
          command: CI=true npm run build
      - run:
          name: npm run deploy
          command: npm run deploy:${PORTFOLIO_ENV}

  deploy_testing:
    <<: *deploy
    environment:
      PORTFOLIO_ENV: testing

  deploy_staging:
    <<: *deploy
    environment:
      PORTFOLIO_ENV: staging

  deploy_production:
    <<: *deploy
    environment:
      PORTFOLIO_ENV: production

workflows:
  version: 2

  testing:
    jobs:
      - test:
          filters:
            branches:
              only: testing
      - deploy_testing:
          requires:
            - test

  production:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - deploy_staging:
          requires:
            - test
      - approve:
          type: approval
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - approve
